### ISSUE TITLE
On/Off sliders don't work.

### ISSUE THREAD

**Issue by Atemu** [SEVENNetworks/AdClear#11] opened 2016-04-21 16:06 UTC
Tapping on or sliding a On/Off slider will not change it's state. Instead it applies the current state again(e.g. disables an already disabled list).

Repro: Tap/slide any slider inside the app.

cpuZ dump: http://valid.x86.fr/a/jjlwkn

**Comment by SEVENNetworks** [comment] 2016-04-21 17:29
Hello Atemu,

Thanks for contributing to the project!

This has been fixed in 500826 and is released on all of our beta channels, let us know how it works for you.

**Comment by Atemu** [comment] 2016-04-21 20:39
Unfortunately I can't download it :/. The only download option I have is the "source code".

**Comment by Atemu** [comment] 2016-04-22 09:28
Ok I found out how to get the beta now.
Looks like the UI is working fine and the tickboxes look way better than the sliders too. But the german filter does not work. I can tick it, it says that it enabled it but I see german ads all over the place!

**Comment by SEVENHelpdesk** [comment] 2016-04-22 14:27
We're glad it's working!

Since we just released these filters, we're still kinda workshopping them to get them to how well we block english. We haven't edited our list much from the normal easylist. Could you give us some apps/sites you see ads on?

**Comment by Atemu** [comment] 2016-04-22 16:00
Some of the Ad-popups I get: 
http://sozialesnetzwerkpreisen.com--get.co/lp/wingame/mb_01/iphonewheel/de/5c/
http://www.aldaniti.net/wingames/mobile_de-iphone/index.php?utm_campaign=premiumgift_de-iphone&utm_source=aldanitinet&pk_origen=1495#page_prizes
http://eu.com-app-ps.com/de2016/0_index0.php?model=One&brand=OnePlus&browser=Chrome%20Mobile&voluumdata=vid..00000003-c26d-4885-8000-000000000000__vpid..e2891800-089a-11e6-8db2-7eb3f47e244d__caid..4ad3587a-9042-448a-9e3b-c73e62f99c89__rt..R__lid..c1e7c7cd-9f49-42f5-8ff2-40e57717586e__oid1..64b71a60-2164-4183-93b9-e1d55375e9b2__var1..188441__rd..onclickads%5C.%5Cnet__aid..__ab..__sid..&zoneid=188441#b

Some of the websites I get ads on:
http://www.mp4upload.com/sk7p47fulqh1
http://proxer.me/watch/5690/1/engsub
https://www.google.de/search?q=test&oq=test&aqs=chrome..69i57j69i60j69i61j0l3.874j0j4&sourceid=chrome-mobile&ie=UTF-8#num=100&newwindow=1&safe=strict&q=beste+preise (google search for something that will definitely give you search result ads)

Websites that should be blocked:
http://www.onclickads.net/

Apps I see ads in: 
Youtube (german ads)
Play store (search result ads, german)
Relay for reddit (Adchoices ads, german)
Tubemate (hoiplay ads)
BSPlayer Free (Adchoices ads, I'll stop listing apps with adchoices ads now)
Every app with Google ads

Filterlists I want: https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters

**Comment by Anarchy8** [comment] 2016-04-25 15:36
Hello, 
Thank you for your input. The issue seems to be caused by the lack of filters for the German List, we have started working on it.
We will update you as soon as we finish adding filters. 
Would you be willing to test the beta version for German ads when it is ready?  

Sincerely, 
Seven Networks Team.

**Comment by Atemu** [comment] 2016-04-25 18:38
Of course I would!

**Comment by DustyWMorgan** [comment] 2016-05-31 02:33
@Atemu I am going to make a separate ticket for the ad blocking issue so it doesn't get lost under this title. You should notice a big improvement in 501194.

**Closed by DustyWMorgan** 2016-05-31 02:33 UTC
Labels: bug
