### ISSUE TITLE
Chrome is not loading URLs

### ISSUE THREAD

**Issue by SEVENHelpdesk** [SEVENNetworks/AdClear#2] opened 2016-02-24 19:32 UTC
Per the [user: ](http://forum.xda-developers.com/showpost.php?p=65486623&postcount=37)

"Many URL won't load in Chrome page loads is nonexistent for almost all the URL's I've tried. Is there a glitch?

This is happening on WFI/LTE/4G/3G
Device: Xperia Z2
Version: Lollipop 5.1.1
- STOCK."

This has been observed in 4.4 as well (27351). The URL sits while loading and never completes. Appears to be related to the certificate.

**Comment by SEVENNetworks** [comment] 2016-03-17 22:47
We have found the root cause for this and a fix will be published shortly

**Comment by SEVENNetworks** [comment] 2016-03-19 01:20
Fixed in 500536

**Closed by SEVENNetworks** 2016-03-19 01:20 UTC
